### ISSUE TITLE
github auth is not working

### ISSUE THREAD

**Issue by TheRojam** [codimd/server#255]
i wanted to use github auth w/ a codimd site.

i my github.app settings are like this
![github.app settings](https://img.therojam.xyz/2020-01-12-github-app-settings.png)

my config.json is this:
```
{
    "production": {
        "urlAddPort": true,
        "email": true,
	"allowEmailRegister": true,
	"useCDN": false,
	"allowAnonymousEdits": false,
	"allowFreeURL": true,
        "db": {
            "username": "hackmd",
            "password": "hackmdpass",
            "database": "hackmd",
            "host": "hackmdPostgres",
            "port": "5432",
            "dialect": "postgres"
        },
        "github": {
            "clientID": "55f5axxxxxxxx4b",
            "clientSecret": "2b682895130xxxxxxxxxxxxx5927b"
        },
        "imageUploadType": "imgur"
    }
}

```
after it i got this 
https://codimd.sportresult.com/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch

but ya, i can read and i can see this i redirects me to https://developer.github.com/apps/managing-oauth-apps/troubleshooting-authorization-request-errors/#redirect-uri-mismatch.

**Comment by SISheogorath** [comment]
Solved by https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$1578846716162QboSg:shivering-isles.com?via=matrix.org&via=chat.weho.st&via=matrix.allmende.io

**Comment by TheRojam** [comment]
after changing my config.json 

```
-        "urlAddPort": true,
+        "urlAddPort": false,
+		 "domain": "codimd.sportresult.com",
+		 "useProtocolSSL": true,
```
it loads github but not still throws an error internal server error....

**Comment by blacklight** [comment]
For anyone still experiencing the issue: the `config.json` option is `protocolUseSSL`, at least on recent versions of Hedgedoc.
